---
title: "Sepsis Monitor Report"
author: "Katherine Giorgio"
format: html
---

```{r setup}
#| warning: false
#| message: false
#| echo: false

library(tidyverse)
library(data.table) ## For the fread function
library(lubridate)
library(googledrive)
library(gt)
#library(tictoc)

source("sepsis_monitor_functions.R")

## Authenticate to Drive, using a token stored in an environ variable
api_key <- Sys.getenv("GOOGLEDRIVE_API")
drive_auth(email = "giorg024@umn.edu",
          token = api_key)

df <- makeSepsisDataset()
```

```{r task2}
#| eval: false

### Task 1: Speed reading
# fread with 50 people (this is the function default) = 10.61 s
tic()
df <- makeSepsisDataset(n=50, read_fn="fread")
toc()

# read_delim with 50 people = 21.22 s
tic()
df <- makeSepsisDataset(n=50, read_fn="read_delim")
toc()

# fread with 100 people = 15.68 s
tic()
df <- makeSepsisDataset(n=100, read_fn="fread")
toc()

# read_delim with 100 people = 57.9 s
tic()
df <- makeSepsisDataset(n=100, read_fn="read_delim")
toc()

# fread with 500 people = 76.19 s
tic()
df <- makeSepsisDataset(n=500, read_fn="fread")
toc()

# read_delim with 500 people = "timeout was reached: [physionet.org] Connection timed out after 10007 milliseconds"
tic()
df <- makeSepsisDataset(n=500, read_fn="read_delim")
toc()
```

```{r task3}

### Uploading to Google Drive

# We have to write the file to disk first, then upload it
df %>% write_csv("sepsis_data_temp.csv")

drive_deauth()
# Uploading happens here
sepsis_file <- drive_put(media = "sepsis_data_temp.csv", 
          path = "https://drive.google.com/drive/folders/1bw6XgCMdGh1DyMIGOm1mPTTDP5rtny5W",
          name = "sepsis_data.csv")
### note for future: I had to delete '?usp=sharing' from the end of the folder path in order for this to work

# Set the file permissions so anyone can download this file.
sepsis_file %>% drive_share_anyone()
```



```{r task4}

### Making the HTML ICU sepsis status report

### Step 1: getting the data from google drive

## Calling drive_deauth() prevents R from trying to authenticate via a browser
## This is needed to make the GitHub Action work
drive_deauth()
file_link <- "https://drive.google.com/file/d/1giyI7visQtm8V_sAt3N_AEuAvH9LYhmy/view?usp=share_link"

## All data up until now
new_data <- updateData(file_link)

## Include only most recent data
most_recent_data <- new_data %>%
  group_by(PatientID) %>%
  filter(obsTime == max(obsTime)) %>% 
  ungroup()



### Step 2: make table of current sepsis patients with their most recent vitals

CurrentSepsisTable <- most_recent_data %>% 
  filter(SepsisLabel == 1) %>% 
  select(c(PatientID, HR, Temp, Resp)) %>% 
  gt() %>% 
  tab_header(title = "Sepsis Patients' Current Status",
             subtitle = "data updated every hour") %>% 
  cols_label(PatientID = "Patient ID",
             HR = "Heart Rate",
             Temp = "Body Temperature",
             Resp = "Respirations") %>% 
  cols_align(align="center")



### Step 3: make plots for all patients who have sepsis that show their vital signs history

colors <- c("Heart Rate (bpm)" = "darkred",
            "Temperature (C)" = "darkblue",
            "Respiratory Rate (bpm)" = "darkgreen")

VitalsPlots <- new_data %>% 
  group_by(PatientID) %>% 
  filter(sum(SepsisLabel) > 0) %>% 
  ggplot(aes(x=ICULOS)) +
  geom_line(aes(y=HR, color="Heart Rate (bpm)"), linewidth=1.5) +
  geom_line(aes(y=Temp, color="Temperature (C)"), linewidth=1.5) +
  geom_line(aes(y=Resp, color="Respiratory Rate (bpm)"), linewidth=1.5) +
  facet_wrap(~PatientID) +
  labs(x = "Hours Since Admission",
       y = "Vital Sign Value",
       title = "Vital Signs Trends for Current Sepsis Patients",
       color = "Legend") +
  scale_color_manual(values = colors) +
  theme_light()



### Step 4: make a table showing the change in measurements between the last two measurements for all patients

# this should look kind of like the first table but with some data wrangling beforehand

#new_data has all info up until now, so that's probably the most useful

ChangeTable <- new_data %>% 
  group_by(PatientID) %>% 
  mutate(HRchange = HR - lag(HR),
         TEMPchange = Temp - lag(Temp),
         RESPchange = Resp - lag(Resp)) %>% 
  group_by(PatientID) %>%
  filter(obsTime == max(obsTime)) %>% 
  ungroup() %>% 
  select(c(PatientID, HRchange, TEMPchange, RESPchange)) %>% 
  gt() %>% 
  tab_header(title = "Vital Sign Values, Change Since Last Measurement",
             subtitle = "(all patients)") %>% 
  cols_label(PatientID = "Patient ID",
             HRchange = "Change in Heart Rate",
             TEMPchange = "Change in Body Temperature",
             RESPchange = "Change in Respiratory Rate") %>% 
  cols_align(align="center")
```

last updated: `r Sys.time()`  
  
```{r}
CurrentSepsisTable
```

```{r}
#| warning: false

VitalsPlots
```

```{r}
ChangeTable
```
